library(rmarkdown)

print("Running scRNATemplate part 1")
render("scRNA_template_PART1.Rmd")
#print("Running scRNATemplate part 2")
#render("scRNA_template_PART2.Rmd")
#print("Running scRNATemplate part 3")
#render("scRNA_template_PART3.Rmd")
#print("Running scRNATemplate part 4")
#render("scRNA_template_PART4.Rmd")
#print("Running scRNATemplate part 5")
#render("scRNA_template_PART5.Rmd")
# render("scRNA_template_PART2.Rmd")
print("Done!")
